# Generated by Django 4.0.2 on 2022-02-21 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health_check', '0002_application_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='application',
            options={'verbose_name_plural': 'Application'},
        ),
        migrations.AlterModelOptions(
            name='status',
            options={'verbose_name_plural': 'Status'},
        ),
        migrations.AlterField(
            model_name='status',
            name='code',
            field=models.PositiveIntegerField(),
        ),
    ]
